[project]
id = "ukpapqssgsxirsgmcvof"
name = "Runes de ChÃªne"

[api]
enabled = true
port = 54321
schemas = ["public"]

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/auth/callback"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.external.google]
enabled = false

[auth.external.apple]
enabled = false
